version: "3"
services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    restart: always
    env_file:
      - .env
    environment:
      POSTGRESQL_USERNAME: ${DB_USER}
      POSTGRESQL_PASSWORD: ${DB_PASSWORD}
      POSTGRESQL_DATABASE: ${DB_NAME}
    volumes:
      - "postgresql_data:/bitnami/postgresql"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 1s
      timeout: 5s
      retries: 5

  app:
    build: .
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env

volumes:
  postgresql_data:
    driver: local
